# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SocialApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocialApp
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'Firebase/Messaging'
	pod 'Firebase/Auth'
	pod 'Firebase/Analytics'
	pod 'Firebase/Firestore'
	pod 'MBProgressHUD'
	pod 'TinyConstraints'
	pod 'SideMenu'
	pod 'ActiveLabel'
	pod 'KMPlaceholderTextView'
	pod 'Stripe'
	pod 'PaymentKit'
	pod ‘PayPal-iOS-SDK’, ‘~> 2.15’
end
